name: 'confido_case'
version: '1.0.0'
config-version: 2

# Must match the top-level key in profiles.yml
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  confido_case:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
